version: "2"

services:
  data:
    image: postgres:9.6
    volumes:
      - /var/lib/postgresql
    command: "true"
  postgres:
    restart: always
    build: ./postgresql
    volumes_from:
      - data
    ports:
      - "5432:5432"
  web:
    depends_on:
      - postgres
    build: ./web
    ports:
      - "5000:5000"
    links:
      - postgres:postgres
    volumes:
      - .:/code