version: "2"

services:
  mysql:
    image: mysql
    build: ./mysql
    environment:
      MYSQL_ROOT_PASSWORD: "morgan"
      MYSQL_DATABASE: "ds-recruit"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always
    networks:
      - ds-recruit_mysql_net

  web:
    depends_on:
      - mysql
    build: ./web
    ports:
      - 8080:80
    expose:
      - "5000"
    volumes:
      - .:/code
    links:
      - mysql:mysql
    restart: always
    networks:
      - ds-recruit_mysql_net

volumes:
  mysql_data:

networks:
  ds-recruit_mysql_net:
    driver: bridge
