version: "2"

services:
  nginx:
    restart: always
    build: ./nginx
    ports:
      - "80:80"
    links:
      - web:web
    networks:
      - ds_net

  mysql:
    build: ./mysql
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always
    env_file: .env
    networks:
      - ds_net

  web:
    depends_on:
      - mysql
    build: ./web
    ports:
      - "5000:5000"
    volumes:
      - ./web:/code
    links:
      - mysql:mysql
    restart: always
    env_file: .env
    networks:
      - ds_net

volumes:
  mysql_data:

networks:
  ds_net:
    driver: bridge
